services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=innovation_practice
    ports:
      - 5430:5432
    volumes:
      - /var/lib/postgres/data